---
title: "Final Project Proposal"
date: "2025-11-07"
output: github_document
---
## The group members 
Miranda Chen *xc2784*  
Huiyi Zhu *hz3023*  
Yiyang Jiao *yj2874*  
Xiaoqian Lyu *xl3494*  
Yuyue Ma *ym3077* 

## The tentative project title
ParkScope — Patterns, People, and Places in NYC Special Events


## The motivation for this project

New York sells itself on vibrant public life—but a city’s real magnetism shows up in how well it shares its spaces and resources. Recreation and cultural events can boost health, knit communities together, and energize neighborhoods. Yet across NYC, population density, demographics, and access to parks vary dramatically. Are we programming public events where people actually are—and where they’re most needed?
Using NYC Parks’ Special Events data (one-off fitness, sports, dance, film, and concert events), we will map and model how event types distribute across the city’s geography and population patterns. Our goal is to surface clustering, gaps, and inequities, identifying neighborhoods saturated with options versus areas underserved. The findings can inform more equitable programming, guiding agencies and partners to place the right events in the right places, and ultimately make NYC’s public realm more inclusive, healthy, and alive.

## The intended final products

**Exploratory Data Analysis:**          
Descriptive statistics: Descriptive analyses of NYC Parks special events, focusing on event types, frequency,  duration, and geographic distribution across boroughs and seasons.          
Visualization: Summarize how event activity varies by time of year, park location, and event category.   


**Spatial and Temporal Analysis**
Using mapping tools and time-series visualizations, we will explore spatial clustering and seasonal trends in park events. This analysis will identify whether certain boroughs or neighborhoods host more frequent events and how park activity changes over time.


**Equity and Accessibility Assessment**
Using demographic and population data from the U.S. Census and NYC Open Data, we will evaluate the relationship between event locations and neighborhood characteristics (e.g., population density, socioeconomic indicators). This analysis will help assess whether public events are equitably distributed among communities.



## The anticipated data sources
Dataset will be the *Parks Special Events* from *NYC Open Data*. This data set includes detailed information on public events held in New York City parks.  
Relevant indices:  
--Group Name/Partner    
--Borough     
--Location      
--Event Name & Type     
--Attendance      
--Category



## The planned analyses / visualizations / coding challenges


## The planned timeline
11/7 Project Proposal Finished          
11/12 Project dataset         
11/14 Project Reviewing Meeting with Teaching Team        
11/21 Dataset cleaning & basic Analysis       
11/28 Visualization and Website       
12/6 Report       
